### ISSUE TITLE
Layihe haqqinda melumat

### ISSUE THREAD

**Issue by samirkarimov** [Gunay099/PragmatechFoundationProject#1]
- [ ] Layihe haqqinda melumat yoxdur
- [ ] Layihe ucun numune goturulen link yoxdur
- [ ] Nece sehife olacagi ve senin nece denesini edeceyini geyd etmemisen

**Comment by Gunay099** [comment]
Readme-də komment yaratdım. 
Layihə haqqında qısa məlumat yazdım.  
Layihənin konkret linki yoxdur deyə qeyd etməmişəm. Bir neçə fərqli saytlardan nümunəyə baxmışam.
Səhifənin sayını müəyyənləşdirib qeyd edəcəm.

**Comment by samirkarimov** [comment]
Good gundelik az da olsa nese edib bura yuklemeye calis ki men gedisati duzgun analiz ede bilim
