### ISSUE TITLE
SASS-la bagli meslehetler

### ISSUE THREAD

**Issue by samirkarimov** [Gunay099/PragmatechFoundationProject#2]
- [ ] SASS fayl bolgun yaxsidir
- [ ] Deyisenlerden istifade etmemisen . SASS deyisenlerinden istifade senin isini ciddi suretlendirer 
- [ ] Ortaq class mentigini arasdir bir az bu da sene layihede cox lazim olacaq
- [ ] container>row>col mentigini tetbig etmemisen umumen bu mentigini tetbig etmek senin layihen kimi layihelerde cox onemlidir

**Comment by Gunay099** [comment]
Salam, 
Sass dəyişənlər əlavə etdim.

**Comment by samirkarimov** [comment]
Tesekkur edirem
