### ISSUE TITLE
Dusuncelerim

### ISSUE THREAD

**Issue by samirkarimov** [Gunay099/PragmatechFoundationProject#4]
- Hazir kodlara cox gacirsan
- Plansizliq hissedirem
- Sadece layihe bitsin deye dusunursen sanki oyrenme ikinci planda galir
- Layihe ve oyrenmeye stabil vaxt ayirmaqda ciddi problemin var bunu mence ciddi planlamalisan

**Comment by Gunay099** [comment]
Salam Samir m.,

Rəylərinizlə bağlı tamamilə razıyam, planlaşdırmaqda problemim var. İndiyə
qədər hazır kodlara öyrəşmişdim, amma sizin dərslərdən bu günə nəhayət
inkişaf elədiyimi hiss edirəm və necə sistemli getmək lazım olduğunu artıq
anlayıram. Hətta bir saatın içində öz dəsti xəttimlə)) bir səhifəlik form
yaratmışam (form-contracts.html), Githubi yeniləyəcəm baxarsız. Bu aralarda
köhnə layihəm var idi yadınızda ilk dəfə sizə müraciət edəndə o layihə ilə
yaxınlaşdıq. Müştərinin səbəbindən yarımçıq qalmışdı . İndi istəyir ki,
bitirim. Təcrubəsizliyimdən biraz ləng gedir, amma inanınki  öyrənməyə cox
can atıram, bütün günümü saatımı dərsə sərf edirəm. Maksimum bacardığım
gücü sərf edirəm.

4 yan 2021, B.e. tarixində 01:03 tarixində Samir Karimov <
notifications@github.com> yazdı:

**Comment by samirkarimov** [comment]
Men de zamaninda eyni problemleri yasamisam ve bilirem ki nece cetindi o sistemden cixmaq yeni hazir kod sisteminden. amma ne geder o sistemden kenara cixsan bir o geder tez inkisaf edersen
